import styles from "./Table.module.css";

const Table = () => {
  return (
    <div className={styles["tableFixHead"]}>
      <table>
        <thead>
          <tr>
            <th>title1</th>
            <th>title2</th>
            <th>title3</th>
            <th>title4</th>
            <th>title5</th>
            <th>title6</th>
            <th>title7</th>
            <th>title8</th>
            <th>title9</th>
            <th>title10</th>
            <th>title11</th>
            <th>title12</th>
            <th>title13</th>
            <th>title14</th>
            <th>title15</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>1</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>2</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>3</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>4</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>5</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>6</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>7</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>8</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>9</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>10</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>11</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>12</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>13</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>14</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>15</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>16</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>17</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>18</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>19</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>20</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>21</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>22</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>23</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>24</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
          <tr>
            <td>25</td>
            <td>test2</td>
            <td>test3</td>
            <td>test4</td>
            <td>test5</td>
            <td>test6</td>
            <td>test7</td>
            <td>test8</td>
            <td>test9</td>
            <td>test10</td>
            <td>test11</td>
            <td>test12</td>
            <td>test13</td>
            <td>test14</td>
            <td>test15</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
};

export default Table;
